-- 학생 테이블
CREATE TABLE KH_STUDENT(
    STD_NO NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
    STD_NAME NVARCHAR2(5) NOT NULL,
    STD_AGE NUMBER NOT NULL,
    MAJOR NVARCHAR2(10) NOT NULL,
    ENT_DATE DATE DEFAULT SYSDATE,
    CLUB_ID NUMBER
);

CREATE SEQUENCE SEQ_STD_NO
START WITH 1
INCREMENT BY 1
NOCACHE;



-- 동아리 테이블
CREATE TABLE KH_STUDENT_CLUB(
    CLUB_ID NUMBER CONSTRAINT PK_CLUB PRIMARY KEY,
    CLUB_NAME VARCHAR2(50) NOT NULL,
    CLUB_CATEGORY VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'ACTIVE'
);

CREATE SEQUENCE SEQ_CLUB_ID
START WITH 1
INCREMENT BY 1
NOCACHE;



-- 시설 테이블
CREATE TABLE KH_STUDENT_FACILITY(
    FACILITY_ID NUMBER CONSTRAINT PK_FACILITY PRIMARY KEY,
    FACILITY_NAME VARCHAR2(100) NOT NULL,
    FACILITY_TYPE VARCHAR2(30)
        CHECK (FACILITY_TYPE IN ('CAFETERIA', 'CAFE'))
);



-- 시설 메뉴 테이블
CREATE TABLE KH_STUDENT_FACILITY_MENU(
    MENU_ID NUMBER PRIMARY KEY,
    FACILITY_ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER NOT NULL,
    CONSTRAINT FK_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES KH_STUDENT_FACILITY(FACILITY_ID)
);



ALTER TABLE KH_STUDENT
ADD CONSTRAINT FK_STUDENT_CLUB
FOREIGN KEY (CLUB_ID)
REFERENCES KH_STUDENT_CLUB(CLUB_ID);



COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE IS '학생 나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학일';
COMMENT ON COLUMN KH_STUDENT.CLUB_ID IS '가입 동아리 ID';

COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_ID IS '시설 번호';
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_NAME IS '시설 이름';
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_TYPE IS '시설 종류';

COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.MENU_ID IS '메뉴 번호';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.FACILITY_ID IS '시설 번호';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.NAME IS '메뉴 이름';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.PRICE IS '가격';

COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_ID IS '동아리 번호';
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_NAME IS '동아리 이름';
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_CATEGORY IS '동아리 카테고리';
COMMENT ON COLUMN KH_STUDENT_CLUB.STATUS IS '활동 여부';



-- 동아리 샘플 데이터
INSERT INTO KH_STUDENT_CLUB VALUES (SEQ_CLUB_ID.NEXTVAL, '축구부', '운동', DEFAULT);
INSERT INTO KH_STUDENT_CLUB VALUES (SEQ_CLUB_ID.NEXTVAL, '농구부', '운동', DEFAULT);
INSERT INTO KH_STUDENT_CLUB VALUES (SEQ_CLUB_ID.NEXTVAL, '밴드부', '음악', DEFAULT);



-- 시설 샘플 데이터
INSERT INTO KH_STUDENT_FACILITY VALUES (1, '학식당', 'CAFETERIA');
INSERT INTO KH_STUDENT_FACILITY VALUES (2, '카페', 'CAFE');



-- 9. 시설 메뉴 샘플 데이터
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (1, 1, '돈까스', 6500);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (2, 1, '제육볶음', 7000);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (3, 1, '김치찌개', 6000);

INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (4, 2, '아메리카노', 3500);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (5, 2, '카페라떼', 4500);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (6, 2, '딸기스무디', 5500);



-- 학생 샘플 데이터
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김민준', 22, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이도윤', 21, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박서준', 23, '컴공', SYSDATE, 2);

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이현우', 23, '컴공', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '강민수', 22, '컴공', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최영훈', 21, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '윤하준', 24, '컴공', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '오서우', 20, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '임지환', 23, '컴공', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정서우', 24, '컴공', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '노지호', 21, '컴공', SYSDATE, 3);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김지후', 22, '경영', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '장우빈', 21, '경영', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '서준우', 23, '경영', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '한주원', 24, '경영', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '조민석', 20, '경영', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '안채은', 22, '경영', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '권나린', 21, '경영', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '송서율', 23, '경영', SYSDATE, 3);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '백민준', 22, '전자', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '홍서진', 21, '전자', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '윤현서', 24, '전자', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최도현', 23, '전자', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이준호', 22, '전자', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정하율', 20, '전자', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '한도경', 25, '전자', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '서지유', 21, '전자', SYSDATE, 1);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '문서아', 20, '디자인', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김규리', 21, '디자인', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박리나', 22, '디자인', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '오다인', 24, '디자인', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '배가온', 21, '디자인', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정라온', 22, '디자인', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이수빈', 20, '디자인', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박나경', 23, '디자인', SYSDATE, 1);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '황유나', 23, '경제', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '민보경', 21, '경제', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '라민재', 22, '경제', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '고서영', 24, '경제', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '임나현', 20, '경제', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '조서준', 23, '경제', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이유빈', 21, '경제', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정시윤', 22, '경제', SYSDATE, 2);


COMMIT;




SELECT * FROM KH_STUDENT;
SELECT * FROM KH_STUDENT_CLUB;
SELECT * FROM KH_STUDENT_FACILITY;
SELECT * FROM KH_STUDENT_FACILITY_MENU;
