-- 학생 테이블
CREATE TABLE KH_STUDENT(
    STD_NO NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
    STD_NAME NVARCHAR2(5) NOT NULL,
    STD_AGE NUMBER NOT NULL,
    MAJOR NVARCHAR2(10) NOT NULL,
    ENT_DATE DATE DEFAULT SYSDATE,
    CLUB_NO NUMBER
);

-- 학생 시퀀스
CREATE SEQUENCE SEQ_STD_NO
START WITH 1
INCREMENT BY 1
NOCACHE;


-- 학교 부대시설
CREATE TABLE KH_STUDENT_FACILITY(
    FACILITY_ID NUMBER CONSTRAINT PK_FACILITY PRIMARY KEY,
    FACILITY_NAME VARCHAR2(100) NOT NULL,
    FACILITY_TYPE VARCHAR2(30) CHECK (FACILITY_TYPE IN ('CAFETERIA', 'CAFE'))
);


-- 학교 부대시설 메뉴
CREATE TABLE KH_STUDENT_FACILITY_MENU(
    MENU_ID NUMBER PRIMARY KEY,
    FACILITY_ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER NOT NULL,
    CONSTRAINT FK_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES KH_STUDENT_FACILITY(FACILITY_ID)
);

-- 학교 학생 동아리
CREATE TABLE KH_STUDENT_CLUB(
    CLUB_ID NUMBER PRIMARY KEY,
    CLUB_NAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_CLUB_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 동아리 시퀀스
CREATE SEQUENCE SEQ_CLUB_ID
START WITH 1
INCREMENT BY 1
NOCACHE;


-- 학생 정보
COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE IS '학생 나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학일';
COMMENT ON COLUMN KH_STUDENT.CLUB_ID IS '가입 동아리 ID';

-- 부대시설
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_ID IS '시설 번호)';
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_NAME IS '시설 이름';
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_TYPE IS '시설 종류';

-- 부대시설 메뉴
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.MENU_ID IS '메뉴 번호)';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.FACILITY_ID IS '시설 번호';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.NAME IS '메뉴 이름';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.PRICE IS '가격';

-- 동아리 정보
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_ID IS '동아리 번호';
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_NAME IS '동아리 이름';
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_CATEGORY IS '동아리 카테고리';
COMMENT ON COLUMN KH_STUDENT_CLUB.STATUS IS '활동 여부(Y/N)';



-- 학생 정보 샘플 데이터

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김민준', 22, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이도윤', 21, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박서준', 23, '컴공', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최현우', 20, '컴공', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정우진', 24, '컴공', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김도윤', 22, '컴공', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '배서준', 23, '컴공', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '윤서진', 21, '컴공', SYSDATE, NULL);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이서연', 21, '경영', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김나연', 22, '경영', SYSDATE, 4);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박지현', 23, '경영', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '서하윤', 21, '경영', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최예진', 25, '경영', SYSDATE, 4);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정민지', 24, '경영', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '하서준', 22, '경영', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '우예린', 20, '경영', SYSDATE, NULL);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박지호', 23, '전자', SYSDATE, 4);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '장현우', 22, '전자', SYSDATE, 5);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '문서준', 24, '전자', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김유민', 21, '전자', SYSDATE, 4);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '서지호', 20, '전자', SYSDATE, 5);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이준영', 22, '전자', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '홍도윤', 23, '전자', SYSDATE, 5);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '백승우', 24, '전자', SYSDATE, NULL);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최예린', 20, '디자인', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김하늘', 22, '디자인', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이지민', 21, '디자인', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '노서연', 23, '디자인', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '강하윤', 24, '디자인', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '윤지우', 20, '디자인', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '오예린', 21, '디자인', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김채원', 22, '디자인', SYSDATE, 3);


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정서연', 21, '경제', SYSDATE, 1);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이진우', 23, '경제', SYSDATE, 5);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '송지민', 22, '경제', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '한지우', 24, '경제', SYSDATE, 4);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '황서윤', 21, '경제', SYSDATE, 2);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '임도현', 25, '경제', SYSDATE, NULL);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '조서하', 23, '경제', SYSDATE, 3);
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '하은우', 22, '경제', SYSDATE, 1);

-- 동아리
INSERT INTO KH_STUDENT_CLUB VALUES (SEQ_CLUB_ID.NEXTVAL, '축구부');
INSERT INTO KH_STUDENT_CLUB VALUES (SEQ_CLUB_ID.NEXTVAL, '농구부');
INSERT INTO KH_STUDENT_CLUB VALUES (SEQ_CLUB_ID.NEXTVAL, '밴드부');


-- 부대시설
INSERT INTO KH_STUDENT_FACILITY VALUES (1, '학식당', 'CAFETERIA');
INSERT INTO KH_STUDENT_FACILITY VALUES (2, '카페', 'CAFE');


-- 학식 메뉴
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (1, 1, '돈까스', 6500);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (2, 1, '제육볶음', 7000);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (3, 1, '김치찌개', 6000);

-- 카페 메뉴
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (4, 2, '아메리카노', 3500);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (5, 2, '카페라떼', 4500);
INSERT INTO KH_STUDENT_FACILITY_MENU VALUES (6, 2, '딸기스무디', 5500);




COMMIT;




SELECT * FROM KH_STUDENT;
SELECT * FROM KH_STUDENT_FACILITY;
SELECT * FROM KH_STUDENT_FACILITY_MENU;
SELECT * FROM KH_STUDENT_CLUB;


COMMIT;









