-- 학교 학생 정보
CREATE TABLE KH_STUDENT(
STD_NO NUMBER PRIMARY KEY,
STD_NAME NVARCHAR2(5) NOT NULL,
STD_AGE NUMBER NOT NULL,
MAJOR NVARCHAR2(10) NOT NULL,
ENT_DATE DATE DEFAULT SYSDATE
);

-- 학교 부대시설
CREATE TABLE  KH_STUDENT_FACILITY(
FACILITY_ID NUMBER CONSTRAINT PK_FACILITY PRIMARY KEY,
FACILITY_NAME VARCHAR2(100) NOT NULL,
FACILITY_TYPE VARCHAR2(30) CHECK (FACILITY_TYPE IN ('CAFETERIA', 'CAFE'))
);


-- 학교 부대시설 메뉴
CREATE TABLE KH_STUDENT_FACILITY_MENU(
MENU_ID NUMBER PRIMARY KEY,
FACILITY_ID NUMBER NOT NULL,
NAME VARCHAR2(100) NOT NULL,
PRICE NUMBER NOT NULL,
CONSTRAINT FK_FACILITY FOREIGN KEY (FACILITY_ID)
REFERENCES KH_STUDENT_FACILITY(FACILITY_ID)
);


-- 학교 학생 동아리
CREATE TABLE KH_STUDENT_CLUB(
CLUB_ID NUMBER CONSTRAINT PK_CLUB PRIMARY KEY,
CLUB_NAME VARCHAR2(100) CONSTRAINT UQ_CLUB_NAME UNIQUE NOT NULL,
CLUB_CATEGORY VARCHAR2(50),
STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N'))
);

-- 학생 정보
COMMENT ON COLUMN KH_STUDENT.STD_NO 	IS '학생 번호';
COMMENT ON COLUMN KH_STUDENT.STD_NAME 	IS '학생 이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE 	IS '학생 나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR		IS '학생 전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE	IS  '입학 날짜';

-- 부대시설
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_ID IS '시설 식별 번호';
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_NAME IS '시설 명';
COMMENT ON COLUMN KH_STUDENT_FACILITY.FACILITY_TYPE IS '시설 유형';

-- 부대시설 메뉴
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.MENU_ID IS '메뉴 고유번호';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.FACILITY_ID IS '부대시설 테이블';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.NAME IS '메뉴명';
COMMENT ON COLUMN KH_STUDENT_FACILITY_MENU.PRICE IS '메뉴 가격';

-- 동아리 정보
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_ID IS '동아리 고유번호(PK)';
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_NAME IS '동아리 이름(UNIQUE)';
COMMENT ON COLUMN KH_STUDENT_CLUB.CLUB_CATEGORY IS '동아리 유형(운동, 문화 등)';
COMMENT ON COLUMN KH_STUDENT_CLUB.STATUS IS '활동 상태(Y:활성 / N:비활성)';

-- 학번 시퀀스
CREATE SEQUENCE SEQ_STD_NO
START WITH 1
INCREMENT BY 1
NOCACHE;


INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김민준', 22, '컴퓨터공학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이서연', 21, '경영학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박지호', 23, '전자공학', DATE '2022-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최예린', 20, '디자인', DATE '2025-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정우진', 24, '경제학', DATE '2021-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김하늘', 21, '컴퓨터공학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이도영', 22, '경영학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박서준', 25, '전자공학', DATE '2020-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '서지민', 21, '디자인', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '한지우', 23, '경제학', DATE '2022-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김유진', 22, '컴퓨터공학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이진우', 24, '전자공학', DATE '2021-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박예림', 20, '디자인', DATE '2025-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최현우', 22, '경영학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정서연', 21, '경제학', DATE '2024-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김도윤', 23, '컴퓨터공학', DATE '2022-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이지현', 22, '경영학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박지민', 21, '전자공학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최하윤', 24, '디자인', DATE '2021-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정민서', 25, '경제학', DATE '2020-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '강하늘', 22, '컴퓨터공학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '윤도현', 23, '경영학', DATE '2022-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '임지훈', 21, '전자공학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '노서하', 20, '디자인', DATE '2025-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '문서준', 24, '경제학', DATE '2021-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '오예진', 21, '컴퓨터공학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '서승원', 22, '경영학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '조서아', 25, '전자공학', DATE '2020-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '유지호', 22, '디자인', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김태윤', 23, '경제학', DATE '2022-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '장서현', 20, '컴퓨터공학', DATE '2025-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '배도현', 21, '경영학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '심하윤', 23, '전자공학', DATE '2022-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '홍지우', 24, '디자인', DATE '2021-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '백승현', 22, '경제학', DATE '2023-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '하은우', 21, '컴퓨터공학', DATE '2024-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '우예린', 22, '경영학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '신주원', 24, '전자공학', DATE '2021-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '황서윤', 23, '디자인', DATE '2022-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '송지민', 21, '경제학', DATE '2024-03-01');

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '김나연', 20, '컴퓨터공학', DATE '2025-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '이시우', 22, '경영학', DATE '2023-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '박시윤', 23, '전자공학', DATE '2022-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '최준서', 24, '디자인', DATE '2021-03-01');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정하린', 21, '경제학', DATE '2024-03-01');

COMMIT;




SELECT * FROM KH_STUDENT;
SELECT * FROM KH_STUDENT_FACILITY;
SELECT * FROM KH_STUDENT_FACILITY_MENU;
SELECT * FROM KH_STUDENT_CLUB;


COMMIT;









